import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f4f6f8",
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1b2430",
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#566172",
  },
  bottomNav: {
    flexDirection: "row",
    paddingHorizontal: 6,
    paddingTop: 7,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: "#d5dbe2",
    backgroundColor: "#ffffff",
  },
  bottomNavItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    borderRadius: 10,
    paddingHorizontal: 2,
  },
  bottomNavItemActive: {
    backgroundColor: "#163b66",
  },
  bottomNavText: {
    color: "#344559",
    fontSize: 11,
    fontWeight: "700",
  },
  bottomNavTextActive: {
    color: "#ffffff",
  },
  exploreNav: {
    flexDirection: "row",
    gap: 8,
  },
  exploreNavBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#e1e8ef",
  },
  exploreNavBtnActive: {
    backgroundColor: "#163b66",
  },
  exploreNavText: {
    color: "#203047",
    fontWeight: "700",
    fontSize: 12,
  },
  exploreNavTextActive: {
    color: "#ffffff",
  },
  workspaceRoot: {
    flex: 1,
    paddingHorizontal: 8,
    paddingBottom: 4,
  },
  workspaceStatus: {
    paddingHorizontal: 6,
    paddingBottom: 6,
  },
  workspaceSceneTitle: {
    color: "#203047",
    fontSize: 16,
    fontWeight: "700",
  },
  workspaceViewportFrame: {
    flex: 1,
    minHeight: 150,
  },
  workspaceViewport: {
    height: "100%",
    borderRadius: 12,
  },
  viewportActionToolbar: {
    position: "absolute",
    left: 8,
    bottom: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    maxWidth: "88%",
  },
  viewportActionButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(211,226,239,0.9)",
    backgroundColor: "rgba(25,55,82,0.88)",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  viewportActionButtonActive: {
    borderColor: "#ffd166",
    backgroundColor: "rgba(35,82,119,0.96)",
  },
  viewportActionButtonDisabled: {
    opacity: 0.42,
  },
  viewportActionText: {
    color: "#f7fbff",
    fontSize: 10,
    fontWeight: "700",
  },
  viewportActionTextActive: {
    color: "#ffe59a",
  },
  workspaceEmpty: {
    flex: 1,
    justifyContent: "center",
    gap: 12,
    padding: 20,
  },
  inspectorSheet: {
    marginTop: 5,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d5dbe2",
    overflow: "hidden",
  },
  inspectorHandleArea: {
    alignItems: "center",
    paddingTop: 7,
    paddingBottom: 3,
  },
  inspectorGrabber: {
    width: 36,
    height: 4,
    borderRadius: 4,
    backgroundColor: "#a9b6c5",
  },
  inspectorHint: {
    color: "#667588",
    fontSize: 10,
    marginTop: 3,
  },
  inspectorTabs: {
    flexDirection: "row",
    padding: 5,
    gap: 4,
  },
  inspectorTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 9,
    borderRadius: 8,
  },
  inspectorTabActive: {
    backgroundColor: "#edf4ff",
  },
  inspectorTabText: {
    color: "#506176",
    fontWeight: "700",
    fontSize: 11,
  },
  inspectorTabTextActive: {
    color: "#163b66",
  },
  inspectorContent: {
    maxHeight: 235,
    borderTopWidth: 1,
    borderTopColor: "#e3e8ef",
  },
  inspectorContentInner: {
    padding: 12,
    paddingBottom: 20,
    gap: 10,
  },
  inspectorSettingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: "#e3e8ef",
  },
  objectListRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#d9e1ea",
    borderRadius: 11,
    backgroundColor: "#f8fafc",
    padding: 8,
    gap: 8,
  },
  objectListRowSelected: {
    borderColor: "#296fa8",
    backgroundColor: "#edf6fd",
  },
  objectListSelection: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  objectKindBadge: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e7edf3",
  },
  objectKindBadgeSelected: {
    backgroundColor: "#296fa8",
  },
  objectKindBadgeText: {
    color: "#496075",
    fontWeight: "800",
    fontSize: 12,
  },
  objectKindBadgeTextSelected: {
    color: "#ffffff",
  },
  objectListMeta: {
    flex: 1,
    minWidth: 0,
  },
  objectListTitleSelected: {
    color: "#174f7c",
  },
  objectVisibilityButton: {
    minWidth: 58,
    borderWidth: 1,
    borderColor: "#c6d1dc",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 7,
    alignItems: "center",
  },
  objectVisibilityButtonActive: {
    borderColor: "#55916a",
    backgroundColor: "#edf8f0",
  },
  objectVisibilityText: {
    color: "#6d7784",
    fontSize: 11,
    fontWeight: "700",
  },
  objectVisibilityTextActive: {
    color: "#356848",
  },
  content: {
    paddingHorizontal: 12,
    paddingBottom: 24,
    gap: 12,
  },
  panel: {
    borderRadius: 14,
    backgroundColor: "#ffffff",
    padding: 12,
    borderWidth: 1,
    borderColor: "#d5dbe2",
    gap: 8,
  },
  panelTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#203047",
  },
  subPanel: {
    marginTop: 8,
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e3e8ef",
    padding: 10,
    gap: 4,
  },
  subPanelTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#2b3a4e",
  },
  item: {
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e3e8ef",
  },
  sceneListRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sceneThumb: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: "#163b66",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sceneThumbText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  sceneListMeta: {
    flex: 1,
  },
  projectThumbnail: {
    width: 76,
    height: 58,
    borderRadius: 9,
    overflow: "hidden",
    backgroundColor: "#edf4fb",
    borderWidth: 1,
    borderColor: "#bed0e1",
    flexShrink: 0,
  },
  projectThumbnailAxis: {
    position: "absolute",
    height: 1,
    backgroundColor: "#c4d2df",
  },
  projectThumbnailSegment: {
    position: "absolute",
    height: 1.2,
    borderRadius: 1,
    opacity: 0.82,
  },
  projectThumbnailFallback: {
    color: "#315779",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 18,
  },
  projectActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 10,
  },
  projectEditor: {
    gap: 7,
    marginTop: 10,
  },
  projectDeleteBtn: {
    backgroundColor: "#fff5f5",
    borderWidth: 1,
    borderColor: "#e4aaaa",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  projectDeleteText: {
    color: "#9f2626",
    fontSize: 12,
    fontWeight: "700",
  },
  projectUndoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    borderRadius: 10,
    backgroundColor: "#edf4ff",
    borderWidth: 1,
    borderColor: "#b8cce2",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  itemActive: {
    borderColor: "#163b66",
    backgroundColor: "#edf4ff",
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1f2d3d",
  },
  itemMeta: {
    marginTop: 3,
    color: "#5b6573",
    fontSize: 12,
  },
  note: {
    color: "#48586b",
    fontSize: 13,
    lineHeight: 18,
  },
  warningNote: {
    color: "#8f1d1d",
    fontSize: 12,
    lineHeight: 17,
  },
  primaryBtn: {
    marginTop: 6,
    backgroundColor: "#163b66",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
  },
  primaryBtnText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  secondaryBtn: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#c8d3df",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryBtnText: {
    color: "#223248",
    fontSize: 12,
    fontWeight: "700",
  },
  dangerBtn: {
    backgroundColor: "#fff5f5",
    borderWidth: 1,
    borderColor: "#d99a9a",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dangerBtnText: {
    color: "#9b2c2c",
    fontSize: 12,
    fontWeight: "700",
  },
  viewerToolbarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  loadingOverlay: {
    position: "absolute",
    top: 12,
    right: 12,
    borderRadius: 10,
    backgroundColor: "rgba(17,33,50,0.82)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  loadingOverlayText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
  },
  settingRow: {
    marginTop: 6,
    gap: 6,
  },
  settingChoiceRow: {
    flexDirection: "row",
    gap: 6,
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#c8d3df",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: "#203047",
  },
  pill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#b3c0d1",
    backgroundColor: "#f8fafc",
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
  },
  pillActive: {
    backgroundColor: "#163b66",
    borderColor: "#163b66",
  },
  planePillXY: { backgroundColor: "#dbeafe", borderColor: "#74abff" },
  planePillXZ: { backgroundColor: "#dcf5e3", borderColor: "#69ca84" },
  planePillYZ: { backgroundColor: "#fff0e5", borderColor: "#ffa877" },
  pillText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#2a3a50",
    textTransform: "capitalize",
  },
  pillTextActive: {
    color: "#ffffff",
  },
  issuePanel: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#f2c4c4",
    backgroundColor: "#fff5f5",
    borderRadius: 10,
    padding: 10,
    gap: 4,
  },
  issuePanelTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#8f1d1d",
  },
  issueText: {
    fontSize: 11,
    color: "#8f1d1d",
    lineHeight: 16,
  },
  backendPanel: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#dbe4ee",
    borderRadius: 10,
    backgroundColor: "#f8fbff",
    padding: 10,
    gap: 4,
  },
  backendPanelTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#274567",
  },
  pairingPanel: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#8cb3dc",
    borderRadius: 12,
    backgroundColor: "#f2f8ff",
    padding: 10,
    gap: 8,
  },
  pairingCamera: {
    width: "100%",
    height: 280,
    borderRadius: 10,
    overflow: "hidden",
  },
});
