import { expect, test, type Page } from "@playwright/test";

async function start(page: Page) {
  await page.route("**/api/worker/**", route => route.fulfill({ status: 503, body: '{"error":"unavailable"}', contentType: "application/json" }));
  await page.goto("/");
  await page.evaluate(() => { localStorage.clear(); localStorage.setItem("math3d.computeEngines.firstLaunchSeen", "1"); });
  await page.reload();
  await page.getByTestId("workspace-nav-graphs").click();
}
const checkpoint = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem("math3d.mixed-workspace.v1")!).entries.find((entry: {module:string}) => entry.module === "graph2d").checkpoint);
const save = async (page: Page) => {
  await page.getByTestId("kernel-workspace-toggle").click();
  await page.getByTestId("kernel-workspace-save").click();
  await expect(page.getByTestId("kernel-workspace-message")).toContainText("Saved");
  await page.getByTestId("kernel-workspace-toggle").click();
};

test("GGL13 guided paths open source-linked copies, preserve edits and mark stale annotations", async ({ page }, info) => {
  await start(page);
  await page.getByTestId("graph-gallery-open").click();
  const gallery = page.getByTestId("graph-gallery");
  await gallery.getByRole("button", { name: "Learn", exact: true }).click();
  const guides = gallery.getByTestId("graph-gallery-guides");
  for (const title of ["Slope and derivative", "Area under a parabola", "Approach an asymptote", "Taylor near zero"])
    await expect(guides.getByRole("button", { name: `Study ${title}` })).toBeVisible();
  await guides.getByRole("button", { name: "Study Slope and derivative" }).click();
  const detail = gallery.getByTestId("graph-gallery-guide-detail");
  await expect(detail.getByRole("listitem")).toHaveCount(2);
  await expect(detail).toContainText("not generated by analysis");
  await page.setViewportSize({ width: 390, height: 740 });
  await expect.poll(() => gallery.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await detail.getByRole("button", { name: "Open guided Slope and derivative" }).focus();
  await expect(detail.getByRole("button", { name: "Open guided Slope and derivative" })).toBeFocused();
  await page.screenshot({ path: info.outputPath("guided-concept-compact.png") });
  await page.setViewportSize({ width: 1440, height: 850 });
  await detail.getByRole("button", { name: "Open guided Slope and derivative" }).click();
  const openedGuide = page.getByTestId("graph2d-guided-panel");
  await expect(openedGuide).toContainText("Slope and derivative · current");
  await openedGuide.locator("summary").click();
  await expect(openedGuide).toContainText("request a fresh tangent");
  const markers = page.locator('[data-testid="graph2d-saved-markers"] [data-probe-id]');
  await expect(markers).toHaveCount(2);
  await save(page);
  const first = await checkpoint(page);
  expect(first.requiredCapabilities).toContain("graph2d.probes.v1");
  expect(first.display.pinnedProbes).toHaveLength(2);
  const functions = page.getByLabel("Graph functions", { exact: true });
  await functions.getByRole("button", { name: "Edit Function", exact: true }).click();
  await functions.getByLabel("Function expression").fill("2*sin(x)");
  await functions.getByRole("button", { name: "Save function", exact: true }).click();
  await expect(markers).toHaveCount(0);
  await expect(openedGuide).toContainText("stale");
  await expect(page.getByLabel("Graph inspector", { exact: true }).getByTestId("graph2d-probes")).toContainText("stale");
  await page.getByTestId("graph-gallery-open").click();
  await gallery.getByRole("button", { name: "Learn", exact: true }).click();
  await guides.getByRole("button", { name: "Study Slope and derivative" }).click();
  await expect(detail).toContainText("resumes your edited guided copy");
  await detail.getByRole("button", { name: "Open guided Slope and derivative" }).click();
  await functions.getByRole("button", { name: "Edit Function", exact: true }).click();
  await expect(functions.getByLabel("Function expression")).toHaveValue("2*sin(x)");
  await functions.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByTestId("graph-gallery-open").click();
  await gallery.getByRole("button", { name: "Learn", exact: true }).click();
  await guides.getByRole("button", { name: "Study Taylor near zero" }).click();
  await expect(detail).toContainText("not a certified Taylor remainder");
  await detail.getByRole("button", { name: "Open guided Taylor near zero" }).click();
  await expect(functions.getByRole("button", { name: "Edit P3 cubic", exact: true })).toBeVisible();
  await expect(markers).toHaveCount(2);
  await save(page);
  const second = await checkpoint(page);
  expect(second.identity.id).not.toBe(first.identity.id);
  expect(second.source.objects).toHaveLength(4);
});
