import { expect, type Page } from "@playwright/test";

export async function checkPersonalGraphFlow(page: Page) {
  const functions = page.getByLabel("Graph functions", { exact: true });
  await functions.getByRole("button", { name: "Select Parabola", exact: true }).click();
  const inspector = page.getByLabel("Graph inspector", { exact: true });
  await inspector.locator(".graph2d-critical-list button").first().click();
  const pins = inspector.getByTestId("graph2d-probes");
  await pins.getByLabel("New probe label", { exact: true }).fill("Saved observation");
  await pins.getByRole("button", { name: "Pin current probe", exact: true }).click();
  await inspector.getByRole("button", { name: "Clear selection", exact: true }).click();
  await expect(pins.getByRole("button", { name: "Locate Saved observation", exact: true })).toBeEnabled();
  await pins.getByRole("button", { name: "Locate Saved observation", exact: true }).click();
  await page.getByTestId("kernel-workspace-toggle").click();
  await page.getByTestId("kernel-workspace-save").click();
  await page.getByTestId("kernel-workspace-toggle").click();
  const original = await page.evaluate(() => JSON.parse(localStorage.getItem("math3d.mixed-workspace.v1")!));
  const originalGraph = original.entries.find((e: { module: string }) => e.module === "graph2d").checkpoint;
  await page.getByTestId("graph-gallery-open").click(); const gallery = page.getByTestId("graph-gallery");
  await gallery.getByRole("button", { name: "My Graphs", exact: true }).click();
  await gallery.getByLabel("Reusable copy title", { exact: true }).fill("My reusable parabola");
  await gallery.getByRole("button", { name: "Save current as reusable copy", exact: true }).click();
  await expect(gallery).not.toBeVisible();
  const copied = await page.evaluate(() => JSON.parse(localStorage.getItem("math3d.mixed-workspace.v1")!));
  const copyGraph = copied.entries.find((e: { module: string }) => e.module === "graph2d").checkpoint;
  expect(copyGraph.identity.id).not.toBe(originalGraph.identity.id);
  expect(copyGraph.source).toEqual(originalGraph.source);
  expect(copyGraph.display.pinnedProbes).toEqual(originalGraph.display.pinnedProbes);
  await functions.getByRole("button", { name: "Edit Parabola", exact: true }).click();
  await functions.getByLabel("Function expression", { exact: true }).fill("3*x");
  await functions.getByRole("button", { name: "Save function", exact: true }).click();
  await expect(page.locator('[data-testid="graph2d-saved-markers"] [data-probe-id]')).toHaveCount(0);
  await expect(pins).toContainText("stale");
  await page.getByTestId("graph-gallery-open").click();
  await gallery.getByRole("button", { name: "My Graphs", exact: true }).click();
  const favorite = gallery.getByRole("button", { name: "Favorite project My reusable parabola", exact: true });
  await favorite.click(); await expect(favorite).toHaveAttribute("aria-pressed", "true");
  await gallery.getByRole("button", { name: "Project favorites only", exact: true }).click();
  await expect(gallery.getByTestId("graph-gallery-my-graphs").locator("article")).toHaveCount(1);
  await gallery.getByRole("button", { name: "Close Graph Gallery", exact: true }).click();
  await page.getByTestId("graph-gallery-open").click();
  await gallery.getByRole("button", { name: "My Graphs", exact: true }).click();
  await expect(favorite).toHaveAttribute("aria-pressed", "true");
  await gallery.getByRole("button", { name: `Open project ${originalGraph.metadata.title}`, exact: true }).click();
  const reopened = await page.evaluate(() => JSON.parse(localStorage.getItem("math3d.mixed-workspace.v1")!));
  expect(reopened.entries.find((e: { module: string }) => e.module === "graph2d").checkpoint.source).toEqual(originalGraph.source);
  await page.getByTestId("graph-gallery-open").click(); await gallery.getByRole("button", { name: "My Graphs", exact: true }).click();
  await gallery.getByRole("button", { name: "Open project My reusable parabola", exact: true }).click();
  const edited = await page.evaluate(() => JSON.parse(localStorage.getItem("math3d.mixed-workspace.v1")!));
  expect(edited.entries.find((e: { module: string }) => e.module === "graph2d").checkpoint.source.objects[0].expression.source).toBe("3*x");
}
