import { applyGraph2DAuthoring } from "../graph2dAuthoring";
import { createGraph2DDocument, type Graph2DDocument } from "../graph2dDocument";
import { editGraph2DProbes, graph2DPinnedProbeState } from "../graph2dProbes";
import { createGraph2DPreset, type Graph2DPreset } from "../graph2dPresets";
import { getGraph2DPresetCatalog } from "./catalog";

export type Graph2DGuidedConcept = Readonly<{
  id: string; title: string; level: "beginner" | "intermediate" | "advanced";
  presetId: string; summary: string;
  steps: readonly Readonly<{ heading: string; explanation: string; tryThis: string }>[];
  markers: readonly Readonly<{ objectLabel: string; x: number; label: string }>[];
  extraCurves?: readonly Readonly<{ label: string; expression: string }> [];
}>;

/** Curated teaching text is host content, not executable document source or a new annotation schema. */
const concepts: readonly Graph2DGuidedConcept[] = [
  { id: "derivative", title: "Slope and derivative", level: "beginner", presetId: "sine-derivative",
    summary: "Compare the slope of sin(x) with its independently authored cos(x) curve.",
    steps: [
      { heading: "Read the slope", explanation: "At x = 0, sin(x) crosses zero with slope 1; cos(0) = 1. The second curve was authored explicitly, not generated by analysis.", tryThis: "Select Function near x = 0, then request a fresh tangent or first derivative in Analyze." },
      { heading: "Find a flat point", explanation: "At x = π/2, sin(x) has a local maximum and its derivative is zero. Numerical extrema are candidates, not proofs.", tryThis: "Inspect the labelled high point, then compare the derivative curve at the same x." },
    ],
    markers: [{ objectLabel: "Function", x: 0, label: "slope 1 at x=0" }, { objectLabel: "Function", x: Math.PI / 2, label: "flat near pi/2" }] },
  { id: "integral", title: "Area under a parabola", level: "intermediate", presetId: "parabola-tangent",
    summary: "Bound the area under x² from x = 0 to x = 1; compare the exact reference 1/3 with a requested numerical result.",
    steps: [
      { heading: "Choose the interval", explanation: "The labelled endpoints belong to the authored parabola. The signed area from 0 to 1 is positive.", tryThis: "Select Parabola and set the Analyze interval to [0, 1]." },
      { heading: "Request integration", explanation: "∫₀¹ x² dx = 1/3 by the antiderivative x³/3. The app's bounded numerical integration is an estimate with method and error information.", tryThis: "Run the area tool and compare its stated estimate and confidence to 1/3." },
    ],
    markers: [{ objectLabel: "Parabola", x: 0, label: "area starts x=0" }, { objectLabel: "Parabola", x: 1, label: "area ends x=1" }] },
  { id: "asymptote", title: "Approach an asymptote", level: "intermediate", presetId: "reciprocal-pole",
    summary: "Explore the separate branches of 1/x without drawing a false bridge through x = 0.",
    steps: [
      { heading: "Two domains", explanation: "The example deliberately excludes [-0.125, 0.125]. The curve has no value at x = 0; no marker or finite sample there is valid.", tryThis: "Zoom towards zero and inspect each branch separately." },
      { heading: "Limit, not a point", explanation: "As x approaches zero from the left and right, 1/x has opposite unbounded behavior. The graph is sampled and clipped; the gap does not prove a limit by itself.", tryThis: "Compare the two labelled branch points and their authored domains." },
    ],
    markers: [{ objectLabel: "Negative branch", x: -0.5, label: "left branch" }, { objectLabel: "Positive branch", x: 0.5, label: "right branch" }] },
  { id: "taylor", title: "Taylor near zero", level: "advanced", presetId: "sine-derivative",
    summary: "Compare sin(x) with its first- and third-order Maclaurin polynomials on a bounded interval.",
    steps: [
      { heading: "Linear approximation", explanation: "Near zero, sin(x) ≈ x. This polynomial is an independently authored comparison curve, not a certified Taylor remainder.", tryThis: "Compare Sine with P1 near x = 0, then move away from the center." },
      { heading: "Add the cubic term", explanation: "P3(x) = x − x³/6 follows from derivatives at zero. On this displayed interval it usually tracks sin(x) more closely, but the picture alone does not bound the error.", tryThis: "Compare P1 and P3 near x = 1; inspect coordinates and use a separate error calculation for a bound." },
    ],
    markers: [{ objectLabel: "Function", x: 0, label: "expansion center" }, { objectLabel: "Function", x: 1, label: "compare at x=1" }],
    extraCurves: [{ label: "P1 linear", expression: "x" }, { label: "P3 cubic", expression: "x-x^3/6" }] },
] as const;

const cache = new Map<string, Graph2DPreset>();
export const getGraph2DGuidedConcepts = () => concepts;

/** Recognize only an intact set of curated source-linked markers. Changed source remains visible as stale guidance. */
export function getGraph2DGuidedDocumentGuidance(document: Graph2DDocument):
  Readonly<{ concept: Graph2DGuidedConcept; state: "current" | "stale" }> | undefined {
  const pins = document.display.pinnedProbes ?? [];
  for (const concept of concepts) {
    const matched = concept.markers.map(marker => pins.find(probe => probe.label === marker.label && probe.x === marker.x &&
      document.source.objects.some(object => object.id === probe.objectId && object.label === marker.objectLabel)));
    if (matched.some(probe => !probe)) continue;
    return { concept, state: matched.every(probe => graph2DPinnedProbeState(document, probe!) === "current") ? "current" : "stale" };
  }
  return undefined;
}

/** Independent opt-in copy: frozen v1 scenes and preview digests never change. */
export function getGraph2DGuidedPreset(id: string): Graph2DPreset {
  const existing = cache.get(id); if (existing) return existing;
  const concept = concepts.find(item => item.id === id);
  if (!concept) throw new TypeError("Unknown guided Graph concept.");
  const base = getGraph2DPresetCatalog().get(concept.presetId);
  if (!base) throw new TypeError("Guided concept source is unavailable.");
  let document: Graph2DDocument = base.template;
  for (const curve of concept.extraCurves ?? []) {
    const next = applyGraph2DAuthoring(document, { type: "create", draft: {
      label: curve.label, expression: curve.expression,
      domain: { min: -4, max: 4, includeMin: true, includeMax: true },
      style: { color: "#9333ea", lineWidth: 2, lineStyle: "dashed", visible: true },
    } });
    document = createGraph2DDocument({ ...next, stableKey: ["guided", id] });
  }
  let pins: Graph2DDocument["display"]["pinnedProbes"] = [];
  for (const marker of concept.markers) {
    const object = document.source.objects.find(item => item.label === marker.objectLabel);
    if (object?.kind !== "explicit-cartesian") throw new TypeError("Guided marker source is not an explicit function.");
    const selected = { ...document, display: { ...document.display, pinnedProbes: pins },
      selection: { objectId: object.id, probe: { objectId: object.id, x: marker.x, y: 0 } } };
    pins = editGraph2DProbes(selected, { type: "pin", label: marker.label });
  }
  document = createGraph2DDocument({ ...document, stableKey: ["guided", id], title: concept.title,
    display: { ...document.display, pinnedProbes: pins }, selection: { objectId: null, probe: null } });
  const preset = createGraph2DPreset({ id: `guide-${id}`, version: 1, title: concept.title,
    description: concept.summary, category: base.category, tags: ["guided", id], difficulty: concept.level === "beginner" ? "basic" : concept.level,
    learningGoals: concept.steps.map(step => step.heading), featuredOrder: null, costClass: "starter",
    template: document, sidecars: [], attribution: base.attribution });
  cache.set(id, preset); return preset;
}
