import { describe, expect, it } from "vitest";
import type { VolumeGrid } from "../scene/datasets";
import { adaptDenseGridVolume } from "./infrastructure";
import { computeVolumeDerivativeFields, computeVolumeStatistics, computeVolumeIsoStatistics, createVolumeAnalysisIdentity, createVolumeAnalysisResultStore, findVolumeCriticalPoints, getVolumeAnalysisResult, measureThresholdRegion, publishVolumeAnalysis, runVolumeAnalysis } from "./analysis";
import { createVolumeTypedArrayStore } from "./typedArrayStore";

const gridFrom = (dims:[number,number,number],spacing:[number,number,number],fn:(x:number,y:number,z:number)=>number):VolumeGrid=>{const scalars=new Float32Array(dims[0]*dims[1]*dims[2]);for(let z=0;z<dims[2];z+=1)for(let y=0;y<dims[1];y+=1)for(let x=0;x<dims[0];x+=1)scalars[x+dims[0]*(y+dims[1]*z)]=fn(x*spacing[0],y*spacing[1],z*spacing[2]);return{dims,spacing,origin:[0,0,0],scalars};};

describe("volume analysis",()=>{
  it("publishes finite statistics, percentiles, histograms, and correlations",()=>{const stats=computeVolumeStatistics(new Float32Array([1,2,2,4,3,6,Number.NaN,8]),{components:2,histogramBins:3,valueUnits:"K"});expect(stats).toMatchObject({sampleCount:4,finiteCount:3,missingCount:1,minimum:1,maximum:3,mean:2,valueUnits:"K"});expect(stats.percentiles.p50).toBe(2);expect(stats.histogram.reduce((s,b)=>s+b.count,0)).toBe(3);expect(stats.componentCorrelations[0][1]).toBeCloseTo(1,6);});
  it("computes second-order derivatives for a polynomial with physical spacing",()=>{const grid=gridFrom([7,7,7],[0.5,0.25,0.75],(x,y,z)=>x*x+2*y*y+3*z*z+4*x*y);const fields=computeVolumeDerivativeFields(grid);const i=3+7*(3+7*3);expect(Array.from(fields.gradient.slice(i*3,i*3+3))).toEqual(expect.arrayContaining([expect.closeTo(6,4),expect.closeTo(9,4),expect.closeTo(13.5,4)]));expect(Array.from(fields.hessian.slice(i*6,i*6+6))).toEqual(expect.arrayContaining([expect.closeTo(2,4),expect.closeTo(4,4),expect.closeTo(6,4),expect.closeTo(4,4)]));expect(fields.laplacian[i]).toBeCloseTo(12,4);expect(fields.validMask.reduce((s,v)=>s+v,0)).toBe(343);expect(fields.boundaryMask[0]).toBe(1);expect(fields.method).toMatchObject({source:"sampled-finite-difference",stencilOrder:2});});
  it("finds the stationary candidate of a sampled sphere SDF and handles constant/ramp fields",()=>{const sphere=gridFrom([7,7,7],[1,1,1],(x,y,z)=>(x-3)**2+(y-3)**2+(z-3)**2);const derivatives=computeVolumeDerivativeFields(sphere);const points=findVolumeCriticalPoints(sphere,derivatives,1e-5);expect(points).toContainEqual(expect.objectContaining({voxel:[3,3,3],classification:"minimum-candidate"}));const ramp=computeVolumeDerivativeFields(gridFrom([5,5,5],[2,3,4],(x,y,z)=>2*x-3*y+0.5*z));const i=2+5*(2+5*2);expect(Array.from(ramp.gradient.slice(i*3,i*3+3))).toEqual(expect.arrayContaining([expect.closeTo(2,5),expect.closeTo(-3,5),expect.closeTo(.5,5)]));expect(ramp.laplacian[i]).toBeCloseTo(0,5);const constant=computeVolumeStatistics(new Float32Array(8).fill(5));expect(constant.standardDeviation).toBe(0);});
  it("measures region volume, centroid, bounds, contact, connectivity and iso crossings",()=>{const grid=gridFrom([3,3,3],[2,3,4],(x,y,z)=>(x===2&&y===3&&z===4)||(x===4&&y===3&&z===4)?1:0);const region=measureThresholdRegion(grid,.5,1,6);expect(region.voxelCount).toBe(2);expect(region.physicalVolume).toBe(48);expect(region.components).toHaveLength(1);expect(region.centroid).toEqual([3,3,4]);expect(region.surfaceContactArea).toBe(80);expect(computeVolumeIsoStatistics(grid,.5).crossingEdgeCount).toBeGreaterThan(0);});
  it("keeps dense fields behind managed handles and stales prior revisions in shared history",()=>{const data=gridFrom([5,5,5],[1,1,1],(x,y,z)=>x+y+z);const tracker=new Map();const make=(label:string,now:number)=>adaptDenseGridVolume({id:"analysis-fixture",label,sourceLabel:label,dataset:{kind:"volume",grid:data},grid:data,tracker,now});const buffers=createVolumeTypedArrayStore();let resultStore=createVolumeAnalysisResultStore();const v1=make("v1",1);const summary=runVolumeAnalysis({volume:v1,grid:data,store:buffers,threshold:5,now:2});expect(buffers.has(summary.derivatives.gradient)).toBe(true);resultStore=publishVolumeAnalysis(resultStore,v1,summary,3);expect(getVolumeAnalysisResult(resultStore,createVolumeAnalysisIdentity(v1),"volume-statistics")?.state).toBe("ready");data.scalars[0]=99;const v2=make("v2",4);const summary2=runVolumeAnalysis({volume:v2,grid:data,store:buffers,threshold:5,now:5});resultStore=publishVolumeAnalysis(resultStore,v2,summary2,6);expect(Object.values(resultStore.entries).some(entry=>entry.identity.volumeRevision===1&&entry.state==="stale")).toBe(true);expect(JSON.stringify(resultStore.entries)).not.toContain("gradientMagnitude\":[");});
});
