import { describe,expect,it } from "vitest";
import type { VolumeGrid } from "../scene/datasets";
import { adaptDenseGridVolume } from "./infrastructure";
import { compareVolumeLabels, compareVolumes, createVolumeComparisonResultStore, getVolumeComparisonResult, publishVolumeComparison } from "./comparison";
import { connectedComponentsLabelMap, thresholdVolumeMask } from "./segmentation";
import { createVolumeTypedArrayStore } from "./typedArrayStore";
const grid=(dims:[number,number,number],fn:(x:number,y:number,z:number)=>number,origin:[number,number,number]=[0,0,0]):VolumeGrid=>{const scalars=new Float32Array(dims[0]*dims[1]*dims[2]);for(let z=0;z<dims[2];z++)for(let y=0;y<dims[1];y++)for(let x=0;x<dims[0];x++)scalars[x+dims[0]*(y+dims[1]*z)]=fn(x,y,z);return{dims,scalars,origin,spacing:[1,1,1]};};
const volume=(id:string,data:VolumeGrid)=>adaptDenseGridVolume({id,label:id,sourceLabel:id,dataset:{kind:"volume",grid:data},grid:data,tracker:new Map()});
describe("Volume comparison",()=>{
 it("produces exact zero metrics and managed fields for identity comparison",()=>{const data=grid([3,3,3],(x,y,z)=>x+2*y+3*z);const object=volume("same",data);const store=createVolumeTypedArrayStore();const result=compareVolumes({a:{volume:object,grid:data},b:{volume:object,grid:data},alignment:"exact-grid",store});expect(result.metrics).toMatchObject({signedMeanDifference:0,absoluteMeanDifference:0,changedVoxelCount:0,correlation:1});expect(result.metrics.norms).toEqual({l1:0,l2:0,linfinity:0,rmse:0});expect(store.has(result.fields.signedDifference)).toBe(true);});
 it("matches known offset and scale metrics",()=>{const a=grid([2,2,2],(x,y,z)=>1+x+y+z);const b=grid([2,2,2],(x,y,z)=>2*(1+x+y+z)+3);const result=compareVolumes({a:{volume:volume("a",a),grid:a},b:{volume:volume("b",b),grid:b},alignment:"exact-grid",store:createVolumeTypedArrayStore(),changeThreshold:5});expect(result.metrics.signedMeanDifference).toBe(5.5);expect(result.metrics.absoluteMeanDifference).toBe(5.5);expect(result.metrics.norms.linfinity).toBe(7);expect(result.metrics.correlation).toBeCloseTo(1,6);expect(result.metrics.changedVoxelCount).toBe(4);});
 it("requires explicit alignment and resamples a linear fixture in world space",()=>{const a=grid([3,2,2],x=>x);const b=grid([4,2,2],x=>x-1,[-1,0,0]);expect(()=>compareVolumes({a:{volume:volume("a",a),grid:a},b:{volume:volume("b",b),grid:b},alignment:"exact-grid",store:createVolumeTypedArrayStore()})).toThrow(/incompatible/);const result=compareVolumes({a:{volume:volume("a",a),grid:a},b:{volume:volume("b",b),grid:b},alignment:"resample-b-to-a",store:createVolumeTypedArrayStore()});expect(result.metrics.norms.linfinity).toBe(0);expect(result.provenance).toMatchObject({alignmentPolicy:"resample-b-to-a",interpolation:"trilinear"});});
 it("uses confusion and overlap metrics for categorical labels and refuses interpolation",()=>{const ga=grid([3,1,1],x=>x<2?1:0);const gb=grid([3,1,1],x=>x>0?1:0);const a=connectedComponentsLabelMap(thresholdVolumeMask(ga,.5));const b=connectedComponentsLabelMap(thresholdVolumeMask(gb,.5));const result=compareVolumeLabels(a,b);expect(result).toMatchObject({totalVoxels:3,unchangedVoxels:1,changedVoxels:2});expect(result.labels[0]).toMatchObject({label:1,intersection:1,union:3});expect(result.labels[0].dice).toBe(.5);expect(()=>compareVolumeLabels(a,b,"resample-b-to-a")).toThrow(/forbidden/);});
 it("publishes both revisions and resampling provenance through shared result history",()=>{const a=grid([2,2,2],x=>x);const b=grid([2,2,2],x=>x+1);const va=volume("a",a),vb=volume("b",b);const summary=compareVolumes({a:{volume:va,grid:a},b:{volume:vb,grid:b},alignment:"exact-grid",store:createVolumeTypedArrayStore(),now:10});let results=createVolumeComparisonResultStore();results=publishVolumeComparison(results,va,vb,summary);expect(getVolumeComparisonResult(results,va,vb)?.payload?.provenance.volumeA.id).toBe("a");expect(results.history).toHaveLength(1);expect(JSON.stringify(results)).not.toContain("signedDifference\":[");});
});
