import { describe,expect,it } from "vitest";
import { exportScientificVolume, importScientificVolume, probeScientificVolume, type ScientificVolumeMetadata } from "./scientificIO";
const metadata:ScientificVolumeMetadata={dimensions:[3,2,2],spacing:[.5,1.5,2],origin:[-1,2,4],direction:[0,-1,0,1,0,0,0,0,1],centering:"point",scalarType:"float32",components:1,coordinateSystem:"laboratory",positionUnits:"mm",valueUnits:"K",missingValuePolicy:"nan",missingValueSentinel:null,byteOrder:"little-endian"};
const values=Float32Array.from({length:12},(_,i)=>i-.25);
describe("scientific Volume I/O",()=>{
 it.each(["raw","npy","vti"] as const)("round-trips %s values and spatial metadata",format=>{const artifacts=exportScientificVolume("golden",format,values,metadata);const imported=importScientificVolume(artifacts);expect(Array.from(imported.values)).toEqual(Array.from(values));expect(imported.metadata).toMatchObject({dimensions:metadata.dimensions,spacing:metadata.spacing,origin:metadata.origin,direction:metadata.direction,scalarType:"float32",components:1,positionUnits:"mm",valueUnits:"K"});});
 it("probes metadata without materializing a second payload",()=>{const artifacts=exportScientificVolume("probe","npy",values,metadata);const probe=probeScientificVolume(artifacts);expect(probe).toMatchObject({format:"npy",expectedBytes:48});expect(probe.metadata.dimensions).toEqual([3,2,2]);});
 it("fails safely for malformed, truncated, endian-mismatched and oversized inputs",()=>{expect(()=>probeScientificVolume([{fileName:"bad.npy",bytes:new Uint8Array([1,2,3])}])).toThrow(/NPY/);const raw=exportScientificVolume("truncated","raw",values,metadata);expect(()=>importScientificVolume([{...raw[0],bytes:raw[0].bytes.slice(1)},raw[1]])).toThrow(/length/);const sidecar=JSON.parse(new TextDecoder().decode(raw[1].bytes));sidecar.byteOrder="big-endian";const imported=importScientificVolume([raw[0],{...raw[1],bytes:new TextEncoder().encode(JSON.stringify(sidecar))}]);expect(imported.values[0]).not.toBe(values[0]);expect(()=>probeScientificVolume(raw,{maximumBytes:16})).toThrow(/safety limit/);});
 it("rejects unsupported compression and honors cancellation",()=>{const compressed=new TextEncoder().encode('<?xml version="1.0"?><VTKFile compressor="vtkZLibDataCompressor"><ImageData/></VTKFile>');expect(()=>importScientificVolume([{fileName:"compressed.vti",bytes:compressed}])).toThrow(/Compressed/);expect(()=>importScientificVolume(exportScientificVolume("cancel","npy",values,metadata),{cancelled:()=>true})).toThrow(/cancelled/);});
 it("exports only explicit external artifacts and no local path",()=>{const artifact=exportScientificVolume("safe","npy",values,metadata);expect(JSON.stringify(artifact)).not.toMatch(/[A-Z]:\\|file:\/\//u);expect(artifact.every(item=>!item.fileName.includes("/"))).toBe(true);});
});
