import { describe,expect,it } from "vitest";
import type { VolumeGrid } from "../scene/datasets";
import { closeVolumeMask, connectedComponentsLabelMap, dilateVolumeMask, erodeVolumeMask, fillVolumeMaskHoles, floodFillVolumeMask, intersectVolumeMasks, invertVolumeMask, mergeVolumeLabels, openVolumeMask, removeSmallMaskComponents, resampleLabelMapNearest, restoreVolumeLabelMap, serializeVolumeLabelMap, splitDisconnectedVolumeLabel, subtractVolumeMasks, thresholdVolumeMask, unionVolumeMasks, VolumeSegmentationSession } from "./segmentation";
const grid=(dims:[number,number,number],ones:readonly[number,number,number][]):VolumeGrid=>{const scalars=new Float32Array(dims[0]*dims[1]*dims[2]);for(const[x,y,z]of ones)scalars[x+dims[0]*(y+dims[1]*z)]=1;return{dims,scalars,spacing:[2,2,2],origin:[0,0,0]};};
const count=(data:ArrayLike<number>)=>Array.from(data).filter(Boolean).length;
describe("volume masks, labels and segmentation",()=>{
 it("matches deterministic 6/18/26 connectivity truth cases",()=>{const mask=thresholdVolumeMask(grid([3,3,3],[[0,0,0],[1,1,0],[2,2,1]]),.5);expect(connectedComponentsLabelMap(mask,6).labels).toHaveLength(3);expect(connectedComponentsLabelMap(mask,18).labels).toHaveLength(2);expect(connectedComponentsLabelMap(mask,26).labels).toHaveLength(1);});
 it("implements binary morphology and hole/component operations",()=>{const center=thresholdVolumeMask(grid([5,5,5],[[2,2,2]]),.5);expect(count(dilateVolumeMask(center,1,6).data)).toBe(7);expect(count(erodeVolumeMask(dilateVolumeMask(center,1,6),1,6).data)).toBe(1);expect(count(openVolumeMask(center,1,6).data)).toBe(0);expect(count(closeVolumeMask(center,1,6).data)).toBe(1);const shellPoints:[number,number,number][]=[];for(let z=1;z<=3;z++)for(let y=1;y<=3;y++)for(let x=1;x<=3;x++)if(x!==2||y!==2||z!==2)shellPoints.push([x,y,z]);const shell=thresholdVolumeMask(grid([5,5,5],shellPoints),.5);expect(count(fillVolumeMaskHoles(shell).data)).toBe(27);const noisy=thresholdVolumeMask(grid([5,5,5],[[0,0,0],[2,2,2],[3,2,2]]),.5);expect(count(removeSmallMaskComponents(noisy,2).data)).toBe(2);});
 it("supports Boolean masks, inversion, flood fill, ROI restriction, and cancellation",()=>{const a=thresholdVolumeMask(grid([3,3,1],[[0,0,0],[1,0,0]]),.5);const b=thresholdVolumeMask(grid([3,3,1],[[1,0,0],[2,0,0]]),.5);expect(count(unionVolumeMasks(a,b).data)).toBe(3);expect(count(intersectVolumeMasks(a,b).data)).toBe(1);expect(count(subtractVolumeMasks(a,b).data)).toBe(1);expect(count(invertVolumeMask(a).data)).toBe(7);expect(count(floodFillVolumeMask(a,[0,0,0],6).data)).toBe(2);expect(count(thresholdVolumeMask(grid([3,3,1],[[0,0,0],[2,2,0]]),.5,1,{roi:{min:[0,0,0],max:[1,1,0]}}).data)).toBe(1);expect(()=>thresholdVolumeMask(grid([32,32,1],[]),.5,1,{cancelled:()=>true})).toThrow(/cancelled/i);});
 it("preserves uint32 label IDs and categorical nearest rules across save/load/resampling",()=>{const mask=thresholdVolumeMask(grid([2,2,2],[[0,0,0],[1,1,1]]),.5);let map=connectedComponentsLabelMap(mask,6);map.data[0]=4_000_000_001;map.labels.push({id:4_000_000_001,name:"Exact",color:"#fff",visible:false,locked:true});const restored=restoreVolumeLabelMap(serializeVolumeLabelMap(map));expect(restored.data[0]).toBe(4_000_000_001);expect(restored.labels.at(-1)).toMatchObject({id:4_000_000_001,visible:false,locked:true});const sampled=resampleLabelMapNearest(restored,[3,3,3]);expect(sampled.interpolation).toBe("nearest");expect(new Set(sampled.data).has(4_000_000_001)).toBe(true);});
 it("merges and splits labels without modifying locked labels",()=>{const mask=thresholdVolumeMask(grid([4,1,1],[[0,0,0],[1,0,0],[3,0,0]]),.5);let map=connectedComponentsLabelMap(mask,6);map=mergeVolumeLabels(map,[1,2],1);expect(new Set(map.data)).toEqual(new Set([0,1]));map=splitDisconnectedVolumeLabel(map,1,6);expect(new Set(map.data)).toEqual(new Set([0,1,2]));map.labels.find(l=>l.id===1)!.locked=true;const locked=mergeVolumeLabels(map,[1],2);expect(locked.data[0]).toBe(1);});
 it("applies and cancels previews and restores data plus metadata without retained buffers",()=>{const first=connectedComponentsLabelMap(thresholdVolumeMask(grid([2,2,2],[[0,0,0]]),.5));const second=connectedComponentsLabelMap(thresholdVolumeMask(grid([2,2,2],[[1,1,1]]),.5));second.labels[0].name="Second";const session=new VolumeSegmentationSession(first);session.createPreview(second,"threshold",1);session.cancelPreview();expect(session.current()!.data[0]).toBe(1);session.createPreview(second,"threshold",2);session.applyPreview(3);expect(session.current()!.labels[0].name).toBe("Second");session.undo(4);expect(session.current()!.data[0]).toBe(1);session.redo(5);expect(session.current()!.data[7]).toBe(1);expect(session.summary().ownedBuffers).toBe(2);session.clear();expect(session.summary()).toMatchObject({ownedBuffers:0,ownedBytes:0,undoDepth:0,redoDepth:0});});
 it("bounds retained undo buffers",()=>{const first=connectedComponentsLabelMap(thresholdVolumeMask(grid([2,2,2],[[0,0,0]]),.5));const second=connectedComponentsLabelMap(thresholdVolumeMask(grid([2,2,2],[[1,1,1]]),.5));const session=new VolumeSegmentationSession(first,2);for(let i=0;i<6;i+=1)session.replace(i%2?first:second,"edit",i);expect(session.summary()).toMatchObject({undoDepth:2,redoDepth:0,ownedBuffers:3});});
});
