import * as THREE from "three";
import { GLTFExporter } from "three/examples/jsm/exporters/GLTFExporter.js";
import { OBJExporter } from "three/examples/jsm/exporters/OBJExporter.js";
import type { SurfaceMeshData } from "./surfaceMesh";
import { surfaceMeshToGeometry } from "./surfaceMesh";

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
};

const buildMeshObject = (mesh: SurfaceMeshData) => {
  const geom = surfaceMeshToGeometry(mesh);
  if (!geom.getAttribute("normal")) {
    geom.computeVertexNormals();
  }
  const material = new THREE.MeshStandardMaterial({ color: 0xffffff, metalness: 0, roughness: 1 });
  const obj = new THREE.Mesh(geom, material);
  obj.name = mesh.label || "surface_mesh";
  return obj;
};

export async function exportMeshToGLB(mesh: SurfaceMeshData, filename: string): Promise<void> {
  const exporter = new GLTFExporter();
  const obj = buildMeshObject(mesh);

  return new Promise((resolve, reject) => {
    exporter.parse(
      obj,
      (res) => {
        if (res instanceof ArrayBuffer) {
          downloadBlob(new Blob([res], { type: "model/gltf-binary" }), filename);
          resolve();
          return;
        }
        const json = JSON.stringify(res);
        downloadBlob(new Blob([json], { type: "application/json" }), filename);
        resolve();
      },
      (err) => reject(err),
      { binary: true }
    );
  });
}

export function exportMeshToOBJ(mesh: SurfaceMeshData, filename: string): void {
  const exporter = new OBJExporter();
  const obj = buildMeshObject(mesh);
  const data = exporter.parse(obj);
  downloadBlob(new Blob([data], { type: "text/plain;charset=utf-8" }), filename);
}

export function exportMeshToPLY(mesh: SurfaceMeshData, filename: string): void {
  const positions = mesh.positions;
  const vertexCount = Math.floor(positions.length / 3);
  if (vertexCount < 3) {
    throw new Error("Mesh has too few vertices for PLY export.");
  }

  const hasNormals = !!mesh.normals && mesh.normals.length >= vertexCount * 3;
  const normals = mesh.normals ?? null;
  const triIndices: number[] = [];
  if (mesh.indices && mesh.indices.length >= 3) {
    for (let i = 0; i + 2 < mesh.indices.length; i += 3) {
      triIndices.push(Number(mesh.indices[i]), Number(mesh.indices[i + 1]), Number(mesh.indices[i + 2]));
    }
  } else {
    const triCount = Math.floor(vertexCount / 3);
    for (let t = 0; t < triCount; t++) {
      const base = t * 3;
      triIndices.push(base, base + 1, base + 2);
    }
  }
  const faceCount = Math.floor(triIndices.length / 3);
  if (!faceCount) {
    throw new Error("Mesh has no triangle faces for PLY export.");
  }

  let out = "";
  out += "ply\n";
  out += "format ascii 1.0\n";
  out += "comment generated by Math3D\n";
  out += `element vertex ${vertexCount}\n`;
  out += "property float x\n";
  out += "property float y\n";
  out += "property float z\n";
  if (hasNormals) {
    out += "property float nx\n";
    out += "property float ny\n";
    out += "property float nz\n";
  }
  out += `element face ${faceCount}\n`;
  out += "property list uchar int vertex_indices\n";
  out += "end_header\n";

  for (let i = 0; i < vertexCount; i++) {
    const base = i * 3;
    const x = Number(positions[base] ?? 0);
    const y = Number(positions[base + 1] ?? 0);
    const z = Number(positions[base + 2] ?? 0);
    if (hasNormals && normals) {
      const nx = Number(normals[base] ?? 0);
      const ny = Number(normals[base + 1] ?? 0);
      const nz = Number(normals[base + 2] ?? 0);
      out += `${x} ${y} ${z} ${nx} ${ny} ${nz}\n`;
    } else {
      out += `${x} ${y} ${z}\n`;
    }
  }

  for (let i = 0; i + 2 < triIndices.length; i += 3) {
    const a = triIndices[i];
    const b = triIndices[i + 1];
    const c = triIndices[i + 2];
    out += `3 ${a} ${b} ${c}\n`;
  }

  downloadBlob(new Blob([out], { type: "text/plain;charset=utf-8" }), filename);
}
